name: rolling_zarr_array_store_binder
channels:
  - informaticslab
  - defaults
dependencies:
  - asciitree=0.3.3
  - asn1crypto=0.24.0
  - blas=1.0
  - bokeh=1.0.4
  - boto3=1.9.82
  - botocore=1.12.82
  - ca-certificates=2019.1.23
  - certifi=2018.11.29
  - cffi=1.12.1
  - cryptography=2.5
  - docutils=0.14
  - fasteners=0.14.1
  - freetype=2.9.1
  - idna=2.8
  - intel-openmp=2019.1
  - jinja2=2.10
  - jmespath=0.9.3
  - jpeg=9b
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libpng=1.6.36
  - libtiff=4.0.10
  - markupsafe=1.1.1
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - monotonic=1.5
  - msgpack-python=0.6.1
  - ncurses=6.1
  - numcodecs=0.5.4
  - numpy=1.16.2
  - numpy-base=1.16.2
  - olefile=0.46
  - openssl=1.1.1b
  - packaging=19.0
  - pillow=5.4.1
  - pip=19.0.3
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyparsing=2.3.1
  - pysocks=1.6.8
  - python=3.7.2
  - python-dateutil=2.8.0
  - pyyaml=3.13
  - readline=7.0
  - rolling_zarr_array_store=0.0.3
  - s3fs=0.2.0
  - s3transfer=0.1.13
  - setuptools=40.8.0
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.8
  - tornado=5.1.1
  - urllib3=1.24.1
  - wheel=0.33.1
  - xz=5.2.4
  - yaml=0.1.7
  - zarr=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7

